# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzE4M2Y5ZWQ3YThjNzcyNjk5NzEwNzA1ZWRkYjNhMTc4NDg1MWVlZTNkZjc4ZTU2MzNmZTJhYTI0Y2FjMDQzNDhkMzQwOWI4MjE1YjAxNDg4NTQ3OGMxYTI1ZWZmMjQ4MDE0N2FiNDU0YTA3ODFjYmU4NWE3NDU0Njk2NjQzZTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
