# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDkyYjlhNjVjYzMwYjVlYmU5OTZkNjE0YjNjMGVkODUzNjNlYmE3MDFjZGViOTg2NGU0ODRkNWE5Y2U0ZDVhZDAyZWIwNjIwODA5ZWNmMTIzYzYyNmEyOWVkOGE4ZWQzZWFjNjM4NDM5MWZiNTgyNDVhZTU0Yzg3MDVjNmU5ZmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
