# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODA3ODg0MmMwMDE3NmM1NGU5ODhiMjFmMDJmMjFkMjU2Zjk2NGIyNGRmODY1ODM1NjVhOTcyZGE5NjFiZjI3ZmFlZjA2ZDViYWI5YzdiZDJjNDg2YzUyYmRmMWFjMDU1NWMxYzc2MTE5NDM1NDY0NDA1ZDMzNmMwNDlkYmI4ZjY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
