# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2NjNDY1ZmIxY2I2YmEwZjE0ZDY3Y2Y3MzM2NDZjYjY4MmE0NzNjZjEzNTliOGU5MjVhNjk5NDE1YzI5OTI0ZDI1YjU0MjFjZDIxMDQwMzExMTI1OTg2YWUwZGM2ZTNmNWQwNGFkOTg2Mzg1YjQ1NzlmYjJiMjk5NjQ0MDk3NzA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
