# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODhhN2Y2Mzg5ODM1Y2M1MjY3Y2JiYmM2YTAxOTFiY2JlOWE5MDdiOGE5ZjE0NTQ0NTI2MDg5OGRjZDU2NjdjYmY3NzYzNmE3YWJlOWRiZDE2YTgxYmUyODU5YWI4YWU2OGQyMDBhNzkxODQ2NjUyNTlhOTJhYTY5M2I5YjMwOGU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
