# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTcxYWQ4MDEzZjM2ZWIzMTZhMzQ1YWZlOGIxNzQyNGFhYjYwMTE0ZWJkNGI3ZTc2ZDhlMDk1Y2Y4MzRiMTUwZjQ1ZWU3M2U3NWMzMTRkZjQ1OTEyOTVlNDY4OTY1MWNlMjg1NDViODE0MDdiYzAwMTk2ZjAyZDBlZjRjN2RhZWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
