# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDJmYzAyOTQ2MjRhNjAxNWM5Zjk3NjQ5Zjk5YzBmNTI5ZTljYmY0NjIxMmYzNzdlMzRhYTBjNmJiNTcwM2E5MTExZWY5Yzg3NTI4ZjJlZGNmZmViOGY1YTUwNjQ2OWVhOTNmZTMyYWI0YmM0MTU3MjVkZDZlNjNiNDQ4YjNlYTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
