# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGM4OGE2YjBmOWMwZThlZGMzN2Y1MTQ2MjNkYTdiMjMyN2E2YjA4NGQyMjJiMzdhY2FkZWJkZDNjMjc2MDcxZTM0NTAxMjBiYzgwMjk4OGQ2YWFkYzZmMTRlZjg5NWU0NjE5NjQwMmRjM2EzYTIzNGVkMGNmMmViMDllMDg3MTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
