# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjU3NTU2MWI1NDNmM2MyMGFhYWNlM2QwZjE4NjNlZjAwMjMyZTUzY2JhMGQxOTM5MjZiMzhmNjQ2ZjFhOTc5YTRmNWE5MDI2ZTVmODk0ZmY2N2E1MWQzNjdjYWFkZTRkNTdlM2ExYjZlYTQzNDk0NzdlN2M0ODMzNDYzNGQxNDk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
