# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODEwMGU1MDE3NDM0YWY5NTAzN2M0MDBjNmJmZmE1Y2I1YzlmY2FjYzRiYjdjYzZjY2M2MjBlZWEyMTBkOGI2ZmNkNWQ1NDdkMDRjMWU0OWY5NzU1MWJlZjY0YThlYTIyMWNiZGFiMTdlZmVjNDIxZmE2ZmM3ZTI3MjkzYTIwODY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
