# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTgwYmM2Y2Q1YWU5MzVlOTM3YzUzNDYxZTliZGJlYTMwNzM1NjRiZDlkMmEyN2JkMTI5NDE2YTBlODc1YWQ2NTdjMmU3MzNiMGRhM2E3MTY0Y2ZmMzIzMmJhMTU1ZDU3ZDg5M2ZiN2ZlMzIyZjJhZjUyMTNmMDhhNjRhNjJlNTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
