# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODA4OTFmODVkNzIzMzNkMjE2YTdiMDYwYzBiY2M2NjBmODM5NzhlZjRkODJiZDJjMDNhNDZiYzIyNWIzMTU4NzA2YWUxYjNmZmMzOGIwOWU5N2U2YWRlNDU2MGVjYjhmNTA3MWU3OTFhN2Y3M2RjZjQ3MDFlMzEyZTAwOWUxNzI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
