# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzY1ZDg0Zjg0NzE3OWMyZTZhZTY4OTIyMGRhMzk4YmFhNzFmODU1NTBjYWVjMTdhYjI1MTIwNzY1ZWZlYmUyMzM0OWQyMjVjY2VlMTQ3ODI0NDdjNjc3NjA3YjlmMDM5NTE1ZDZmOWI2YzY0NDlmNjY0NDhhMGM0NDI3ZDgwOTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
