# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2NjNjc2YjBhMDc4ZDQ2ZmE3OWM5NzkyN2Y5NmM2OWMwOTBkYWQ0NDMyZGU1NWE0ZGMwYjYxMDZiM2Y5NTUzYzA3NTU0OThiZGVkNzM2ODc2NDdlMWRmYWU3MDY1NTU1MjI0YjY3YjU4YWQ4ZjBkNzQwNjM2ZTU1OGNjY2UwMjM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
