# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjNkN2Q4Nzk1MzJjMGZiZDY2YThjNWU3ZDQ2N2FhMDk5NmMwZDYyYzcxYjUxYmExMmViMWFhMjdmNjEzMWE5YzY2M2RkODA0MWNiNmIyOGJkNDQzMzgwMTk2YzUxYmQ1NDRlYmE4MGFhYzE1YjMyNWQ2ZGQ4NmZlNTIyZDZmNGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
