# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWQ3YWU5NTU4ZDEwNDUxMDUzYTcxYTc5MjJiNTlhMDI1OTlhYTc2ZTFkYzU0ZjZjMzI0N2NkMWUxNjVkNDRiMmNkMzFhYTcyZmFjYmE5YTAyMDljYzI0NjI0ODkxZGY5NWFjNDU0ZWY3YzdkN2I3ZTZmZDI2NmMxNzQ2ZTM0MDE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
