# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTllY2QwOTVkZWQ2NzlhNTVkZjg2MDY1Mzg4MzZjZjQ1ZWZiZjU3ODgzMzJmNTFlYzNmOTgyYjNlMmE3ZmI0ZTY5MmE2MDE4MjU2ZGY1NzgzY2U2NjU3ODBkN2Y5NzhkZmQ3NzgzM2ZiMTUxMWZhNmQyMDlmYzUzNGQ1MTJjNjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
