# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjczODE3MDhiMDRjMmU5ZjNhYjVjOTIyMDg5NzU3MTdjMzBjMTYzNDQyMzY2YWQ4MTAxYTkyNmZmMWEzZDFkMGIwOWJkODkyY2JhMDJjMzZkZTFkNmQ2ZGYxMmQ0OGI1ZTM4OTE4ODBlMGUwMGYwZTYzY2VjZDJmMGJiZjEyMzQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
