# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjUyNzYzM2RiMGVmYzE2MmUyZThiYWJiOGM2M2FhZWFkMzAwMDMwMjM5MjY4MmI2N2IzODAwNzExNzlhMmFjY2QyMWZlYWVkOWZlNDU2YzJmYWY1Mzc4NDgxMGM4NjZjNTc4MjMyODE2NWRlMjc3ZWRjYWI5ODZiMDdiNDIzNzY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
