#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NmY1ZmZlNjNkNmVmZTgzNGE3NzY3NTQwYWUzNTI2ZjMwNGY0ZjkwMGRkNTQ4Y2E0Yzk2NzQwNGIyMThlZDBjNWNiYThjMGZkYTM4NzMwZTlmZjk4NDZjZmVlNGY0NDI3NDY4NA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
