#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTE4NGU0OGVlYmE3YmE3OTZmNzdkYjA1MDAwMmRlM2JlMmJkNTY0OWFhNDg1ZTllZWVlNWE4NjEwYmY5ZjQ1NmE1NDBiZTczZjc0YmI4OWZmYWRhMDk0NGRlODFhOTc0MzZjZQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
