#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTJhMjA5OGRhZDczNzdmN2ZiZTZmNjJiNjE4Zjg4NTBjYjI3NmI4ZWRiMGU1YWYzNGZkOWY5ZTQ2YjFmMzkyNmY1ZDUzODU5MjY4YTkyNDUxZDlhNWViNzgzM2Y0MjU1MzViMA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
