#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ODc2MzE0ZjNlMDlkMmUwOTZiMzY0YTM2MmQ0MDNmN2I2NGZlYTE1YjMwNDQxNmY0MmEzMTI1OGE2OWIyZWU2YmJmYzAxNjJkZTlmMmU1YjI5ZjgwMzRlMmNlZTBlY2U5NzNiMQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
