#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MThhMmRjMWFhN2UxMjc2NjRkZjA0MTc0NDg0ODMzNDc3NzNkY2EyM2Q1NmVhZGY1MzZhMDZkOGNiOWZmODA3MzUxNzQ4YjQzNDIzZWMxYmI5ZjMwODlhYzcwZTFkZjA5MWNmNg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
