#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjE1MzBhMDRhYjhlMmY4YWFkMjI3OTAyYmY1YTM2MDJiYjdjZWZhZWU2Njk4YTZmZGYyOGE5Mzk4ZmQ2NzE3NzQwNzBmNWIyNmYwOGYzMTI1ZjllYjM4ZGIyNjA3M2ExOWJmNw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
