#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Njk3MGVlNDk1NDc3YTRkYzcxMzA5MjFlOWFhN2ZjMzA1ODE3M2JmNzE1Y2QwNWUzMGYyYzg3YjdmNmQzMzQ5MDkzMmI0ZThmMDY2ODFhOTljMThiMGQwOWFiMThmNjIwZWZjMw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
