#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NTFmODkzYTAwNzMwNjA3ODdkZjBkNmU4ZGNjMmUzODgyYWRkMjcyZDA4N2VkZDg2N2JiNDUzYmZiNGUwYTg4NWJmN2YxMjZmOTgzZTQyOTNjMDc5MGNmMjE3NjE0MzgzMjExZQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
