#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTY4MGE0ZDJlM2JmZGMxNGFjYmI2MzgwM2VlOWRjZTdkYzQyYWU4OGM2YmVkZTI4NDBjMzY1NTRhMGQzMzYxMmM3YWRkOWRhMWIyNTIzY2YzMzNlZTE1Nzc1NmVlOGEyYTNkMg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
