#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MGJjNzFiY2E4OGFkZDgxMTliMWY4NzExMzU1NjA4MTM5OGNmODNhZjhiODEyMjM2NzI1NzIzZTU0Y2Q2YzQxYmNmMDljNjU5ODEyZTgzMmU2M2YyNjZiMDY0M2NiYTdlNWY2Ng==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
