#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YTliNjZiZDlmODAxNTQ0ZDNiZGExODVhYjA3NzBjM2M1MDdjYWI4YmY1NDhmOTE2YmQ4OTUwZGQ2ODVmODBlODkzOWM2Y2M1MDI2NmU5YzhkNzAwN2FlZjBmODVlMjlkYmM4OQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
