#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MzQzMDdkNTJhODM3ZTNiOTY3MWFkYzIyM2I5OTAzNjE2MTg5NGJkODVhNTJkMzEwMDMzZGY1NmYwZTA2YjYzODA2NzZiYzM2MTJjOTNlZjNkMjQ2NmI3YWQyMmEwNjFiZTY2Yg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
