#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Y2Y4Nzc4YzcxYzMzYzRmYWIzM2IwYTM0N2FjM2I2YzkxNmJkOWY2YmI4YWJmMDIwZTM4ZDQzNzg2ZmZhOGY4MmQxYzk4M2NmY2NhZTI0ZThhMDg4NWNhNzMxZWRjY2ZiZTVhOA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
