#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NGI2NzA1ZWU3OTExZThlZjBjYjIwYTlkNTcxNmI1ZGQ1NmZiZjY3M2I1MTUzYzk3ODc0MmZlMmQ4NGFjNmY1ODZlYzZiYjBhYzdlODBlMzczNjU1YTlhMWEzYmE5NGZmYmQ4Yg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
