#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTA4YzExZTJkZWQzMThmYjNhNDVhMmU1ZWVlOTlmNTMyZWE1NGM2ZDM1MmUyOWEwMTQwMjNiZWNmMzk4MzQ0MmIzMjY4Mzk1ODk4OGVjZTcwYjE3NjYwM2U5MjE0NWY5YjU0Yw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
