#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MzNhMmUwZDNmZmViNWFhYTljMTRlYzNiMjExZTM5ZDcxYzBiM2ViMjQxOGYyNzY4MTY1ZDFkMWIwZDQwNGM5MGVkNzJiMzQ1ODk0NzBjOGU0MjliMDQyMTVkZmMzMjc3MTY1ZA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
