#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjMxYzYwOTAxNTVmYTlhYTA4OGY2MDMzOGEwZDRmOWIxYWFmZWQzNmM0MDIwN2ZmMDE5MzMzM2EyMjhiOTRmNGVlMWU5YmZjMDVlMzg3ZWY0ZGZiNjM4NTI0YTEyNzg2MTY0Mw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
