#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjM4OGQ5OThkYjM0MThjOWZiMmQxZjgzNjFiYTFkYjAwMzIyOTkzODBhMzEwYmQwMjgzYTY3ZDA4NDI1OTI2ZTViNDVhMjEzZDg0NWFjZjkxMDc4MGYyM2IzODdmYTY2OTkxNA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
