#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NTI4OTkxYTM3YzBjZDQzMmEwMjgyNzg2MmNkZGIyMDI1YjQyMGYxOWY4MjJmMTE2YWNiOTMzZmVkN2QyMDJhYzUyMmEzNTdjZTQwMGEwZWM5OTBkMWZmZDYzZTlkODZiMzA2MQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
