#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTY3YzZhNzg5YmUxMWFhZGVhNjgzZGFhYTg0NzcwNGZkMWY0MjNmYmY2OGFmOTczMjlhYWUxZTljZjQ4NWQzMTQ1ZjkzMGE2YjVlMDhhNzI4ZDgyMTAxYWY1OThmYTM5NzZiYw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
