#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YTEzYmI1ZDFlYTJhZWY2ZDU1NzhjYjM1NDczNTdjZGU3ZGZjZGEyMDg4ZDY5NGFmNDZlOGM3OTNiM2ViZWQ5ZGY0ZTAwMjNkZjFjMmE0MzcyMTFiMjk5ZDA5YWQ2MWNhMDIyOA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
