#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YzVjNjFkZDQzNDBhYWE0YjdiYzZmNWUzYmIwNzBjMWIzY2RhMmNlNWQzNTY5MjQ5ZTFiYzc5OTE4NWRmYWFjMjlmMzIyMzJkN2NhZmM5ZDdmNTc3YTg4NjVkMGMyMzI2NmRiNQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
