#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OWZkMjkzNmYwNGIyODg2YTNhZGUwODc0NzM4MGFkNTEzNmI0M2UwYjEzZDNmYTlkMjc5NWJlZWRjYWJhMTdjYTU1MWNkY2YxM2E4ZjQ2YTY5NDZiNWVjNmIyM2I5NDYxNjc4Zg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
