#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDUxNGRiMDJhMGRmOTQ2ODM5ODFjYTdhNmU4ODVhZDNkN2UxMWQzNTExY2ExYmNlYjUyNmRjZDljMDU3MTllNjI1YTJjMGRmOWNhN2IzOGU4YWJlODcxNjVmNWY3N2MyZTU0YQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
