#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2NiM2QzMjI5YTMxODNkYWM5OGRkM2I1MDhiYTRhNjJkYmM1ZTE4YWM1NjhhYjYwYTliZWU3OTMxYjJmY2U3MDQwYjdjYzQzOTU0OTJkMDQ5OTMyNzE1NTFhMTVmNzYzMmIxOA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
