#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTgyZjljNTBhYzU3ZjMzYjY5ZWMwYTgwODYzZGRhYzJjNWZjMjUwMjYzZTgyZGQ2NmMxZGZjNThiZGVhZjM5ZDIzZGE3ODljOGNlOTY5OTEwZGNjZmYzYzYyZDBiZWFlZjYwZQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
