#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MzFmMTNlZTE3NWYyOGI1MmJkMDVkNTY5NGI0MGZhNThiNmQ3MTM1OGYyZmIzMDVjNTgyOWNhYTRiYjhiYzkxNGY2ODljMDYwOTRiOThkOWNkMWYwMTAwYjAwNmQxMWIzZjllOA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
