#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2EwYjUzYTIzNGE3ODU0MDI5YjdmZjNmNDY0NDA2OTlhY2ViZmI1MmJiMGYyODkzOGYwZjY4MTYxM2I5OTU3ZTdkNWUxMDViNWVmZWMwNDgyNDk0MmEzOGFjYjhiYjIwMDM0ZA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
