#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MGQ1ODg2NTM5ZDhkMTJiZDk5YjY0OWU1YWQyODhkMmI4ZmIxYTNlM2I4OTQyMTllZGU2YmI5NWZhNGU4ZDM2YjMyMmZjZWRiMjJmMzBkZGU3OTBjZmJhYjBjOTFiYzQ4NzI5Yg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
