#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmQ2MTA5ODk3NjhmM2Q3MGIxNjRkNTc3MmU3MzRhNWY5MmQxMTBlNDBkZjVjNGZkYWMyM2YxNGQ4MTgwN2ZmMWVlMGNkZDU4NTQxYzJmZDMxYjIyNTk4OWZiOTNkZjI4NzdmOA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
