#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTg1ZDI0N2IyMDI0NjBjYTU5NzY3YzFiNTlkY2NlNTMyYTdlZGYzMmI2NzVmNjk0YTQxMzQzODM3M2NmZDMxNzE3MjFlMWQzNGVjODdlMzExMzA4YjFiOTJiZjQ0MGY5ZDRmYg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
