#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjM2MzM4YTY0NDBjMTk0M2NiNzNlMjEyZmQwZTVjYzgyZmM3ZGQ1Zjc1MmNiYTVmNDQ1YTUwNGExZjk5ZjAzZTI1OWJhZmNhNDU2OTM2MzdmZDI5ZWU1NTE3ZGJjNzUxNDVjYQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
