#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTM0MWQxYjI5ODIzNDliNDNlMjMxZTAxYmI5YTdhYmQzYzNjMmYzYzVkNDA3ZGQ3YjEzODdkMjEwNGQyYzViYzhkYzU3M2I0ZDZjZWRhNjliYjdlMTFmMmZiODNjNjZkODZkYQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
