# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjIzNTYyYTY4ODI0M2M2MzJlYzdiMzViN2MyMTUzZTQ0NjViZTA2MjExMzlkYWRjM2ViOWE3NDJkM2FlYjU3YWZjZGRkMjM3NDVmNDk3NjlmN2M5MzA3ZjMwODhmMTE1Y2I4Y2RjN2I0OTdlZDdhZDA2MTk4MTM1YjkwOGFlNDA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
