# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmQ1MDI1YmJlNmRlZGI3NDAzMWIzNGU1MzM5ZmIxZGU1YWMxNjMyMTk3YTEwMjU1MmM1NjZlMDU4ZDI0ZDlmOGEyMzZkODc2Yzc5OTBjOGFkYWRiOTQ3Y2FiZjMyZmI3MTRjNjM1MDI5ODg2NjcwODhjNjlkZWUwNGZkNDBkYjA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
