# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjNmZTY3ZWY4MzdkOGU1MTcyYWFjNzlmYjJlNTYxMmFkOGI1OWY5YmZjY2Y2MzRkM2JkNWZkNGU2NDg4NWI0M2JjYmJkZDYxOWVjOTZlZDViOGE0MTBmNmYwMzFiNTYxNTc1MGJlOGU5Y2YzYWQ3ZDUyZjdmNWM5MjYxODE1MmY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
