# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2VhZDVlYTkwODM3OWJmNjlmNjJkYTZmN2NjNTVmMjY5MGEzZWY0NDczOTNkMWJkYjk3MGY0YjdjYTJiNjVmMzkwNGVhNThkMzQzYTdlZmUwYmNhOGNmNDM1NzMyYjhkODIxNjgzYzk0ZjE3ODVjNzkxZTZiNjc4ZTI4OTRlOWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
