# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZGMyMjIxZTgwNjlkNWQyYzczYTk1ZjVhODA0ZDk1MDU3YTE1ZDBlZmQ3MTQ0NjY4NGU1MTZiZTM3MzE0NmM2YjkzNmY0NDQ1ZGIwYzc3NjA0ZDBjZDYxM2E5NTYzNzIxMDMwMDNhMzk2YTQxZTdmMGFlZmEzNTliODc1YmY0NDU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
