# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzIxYjVjNWJiMzE0Y2I1MDQ2YmVjMTI4YTk4ZjhmYmEzZTZjZGUwMzBlZDBkMTNiNzAwZTFkMWNjNTBlMzk1OGVjODI0ZGU3NjQ0Njc5NzAzMzVhYmU4NzVmNmVlOTBlODhjMWZmY2MxZDU0ZTUyZGIyMmQ2MWQxODVjMDM5OTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
