# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2Q1YmI5MjBjODM4NzdmYzIzNTVkZmM3MTNhYzQ2ZDBjOWU4NjEzNGJkODcyYjYwZTJiZDg3ZDI4NjY0MjA1NmFmMjM2NjRiN2JjZTJmZTc2YWYyODg0YTQ3NGQ3MTMwOWMxOGQ2NmQyMTkxOTY0YWYwZWYyYTU1ZTZkY2QzYTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
