# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmEzMmMwMTQ5YTJhYWE2ZmMzYWY3NjYzMWVlODBjZDYxYzFjNWY4OGI1Nzg2MGYxODg5YzZhODdlN2ViN2NiODUxNjBmODg0OTdmMzA1MTlhOTU5ZDdhZjBjOTg5YWUzNDc3NjU1YzE5NDA0YmE5YjY1NDAzZTQ4ODIyNWQ5NmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
