# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmExMTIxMTYyZTZlZTliZjFkZTAzZDVhNDNlMDQzYjE5NzdjYWZlNGJmMmY2OGE3ZTNjYjIzZWE4Y2MwY2NlZWQ0MzQzYTZiYTkwNDMwZDVkZWMwZTA0YTI2NTdkNmJmZjE0MWU1NTA1MTVjZjljOWNkOTJhOTBiNDZkYTNkNmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
