# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTc3NTgxOTU3NWRmODg3MDlmZTI4MDIzYzdhY2NmYTQzZmMwMDQ1NDQzYTAyODcyMjk0NDEyZGQwNjgzNDdiMTk1ZjZmYWZiMGU1NWNjOGZjYjI3YzU3OWMyMjAwYzIzMTExYjNkMmNmMDdkZmQ0NDIyZGZjMmYwZjY4NDhjZWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
