# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmU5NDY2NGY5ZDk3ZTI4OGY1YzZiZWViZTBkOTA2NDY3ZDA3YzMzMWNiZWNiYTEzY2FlMGI4OWE2OGMyYjI1MTM2MjE3ZWFkM2FjOWY4ZDc1NTIxZWVkOWRhZDk0N2M5YzMyODhjNjkzZmFkZjk5YWM3YWY4YzcyOGQ4N2NjY2Q=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
