# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzcxY2Q2MTU0YTM2YzRjNzZhNjM4ZDEyNGVkYjM2MzAxODk1ZjI3MmI1ZGM0NDg5YmIxZGM1NWVkMDhmODEyODZjNWJkYTM5NzQ4N2U4NDI4MzgyYTlhN2UxNWI2YjgyNGY3ZTg4OWRiZTdiNTA3MmZiMTk3ZDViNGUwMTc1ZjQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
