# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2EwYjBiNTgyYjMxYmY0ZTVlNjBkYTM1NzIwYWEwNGZjZGFiMzk1NTcwYzRmYjc2MjM5ZWZmZTgzYzEwZTM0MmFmNDMxOTc1ZGQxNTViMTFiNmZhOGE2NjM1MWE0YmY2ZmQ5Njg4ZjI1MDc4ZjE4MGMxOWEzNWJmYzQ3OGYwYTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
