# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGViNjg5M2UwZTFhY2E0MWEwNDBjZWQxYmFkNzQ1Y2RjNGZkMDFlMjFiZmFhMTM0NzRhZmYxZmY5ZjI1ZTU2MDI2Yjk2M2MxZDBkODZlYjU3YWJmMTI2YWFjMDFhOTdlMzQzYzdkNmJlMDVhNTEyOGUzNGQxNDE2ZjgyOTc1YjA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
