# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjQ4MzllZmZjYmZjZWQwYjc5M2FhMjY3ZmVlYzdkNzgwZjA1ZTNkYmYyOTdiMmI2Nzc4MzM3OGNhNmI0MDAwODJhODhkYmI0Y2JiYTc5ZTQzMDk5ZTA1OGNmNDA2OWY4M2QzZDg3NGEzNzhhNmIxZDYxMThkY2QyMzdhZWI4Zjc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
