# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTRmNjYzZTQ5MWI2YTAyMGUwNDRmYjY3ZmQ0MjcwNWVhZDIxZGI3ZDc0YmRjYzRmNTBhN2VmZmRiMDlmMTdmNmE4ZGIxNjlhZDIyOWI2ZDU1MDFjOWE5NmM0NmI2NjAwMWVkYzY1MjlmODViZDUyMWFjZWQ4M2Y0ZWNkMTcwZjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
