# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWQwNDQ2ZWU5OWEzM2U2ZGUyZTBmZWMwMDU3NGE2N2IyOTZiOGM3NmJkMDczMGJlYmU1ZTVkNDgzOWU4ZTY0NDI0NTQyNjUyNjZkMDVjYTk1ZjIxYjkyMDQ4ODBlZjdlZDE2ZGI5Mjk5NDFlYzAyNWEzMzAxMzcwNzA4Y2FkZjU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
