# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmM4YTQ5Yzc5OGY5MGExNWJkZmE0NmJiNjkwODJmNDM3M2E5OGQ0MjE2YmE1Y2EzYWJmMmI4YjQyZGM1OTEwZTY0OTNiOGM0NDdlYjQ3NGVjYmFlYWM2MjViZGRmZjgwNWVjY2U0MTVlZWIxZmUwYTdkMjE0ZDQ1MmY5MzRiMTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
