# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmMzOTJmNGE1ZjQyMzUxZDdmNDVlOTczMjM2ZmUyMWE1MTBmZjAxNTI5MmE4OWE1YTAzZjY4NzU2M2ZkZTA0N2Q5NmIwMTQ4NGI0M2UwOWNlYjc4NjU4ZWYxYzMwM2FjMzllZTdhNThhZWQ2NTk5NmViY2E1ZmFhZTRkYWI3YTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
