# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YThkMGYxNGM3YjVhNjlkNmY4ZWNiZjNlZTJmOTExZjFkODM1MWUyYzdkMDFlYjc5NDhjMTc1MTY5YzMzMzdiMTE3ZjY2YjkwM2JmOTJmYzM3NjY0MTRjZjIwZjNhZmZkZDBiODRjNzMyYzM4NWU2ZjdhN2JlODlmYTdiMjkxYTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
